#!/usr/bin/env python3
#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""gluten-ut suite tooling.

Gluten runs vanilla Spark test suites by declaring, for each one, a subclass that
mixes in a Gluten test trait:

    class GlutenBucketingUtilsSuite extends BucketingUtilsSuite with GlutenSQLTestsBaseTrait {}

...and by registering that subclass, plus the tests to skip, in a per-backend
`BackendTestSettings` written in Scala. Both are pure boilerplate that has to be
duplicated for every supported Spark version. This script replaces them with two
data files per Spark version:

    src/test/resources/gluten-ut/suites.txt            the suite catalog
    src/test/resources/gluten-ut/settings-<backend>.txt what to run, per backend

`generate` turns the catalog into the subclasses at build time (nothing to commit,
nothing to review); the settings file is read at run time by
`org.apache.gluten.utils.DataFileBackendTestSettings`.

Subcommands
    extract   Scala sources -> data files (one-shot migration, per Spark version).
    generate  Catalog -> Scala sources under target/generated-test-sources.
              Run by maven; safe to run by hand.
    verify    Generate in memory and diff against the hand-written sources, to
              prove a migration is behaviour-preserving before deleting them.

Standard library only, python3.6+.
"""

import argparse
import os
import re
import sys
from collections import OrderedDict

LICENSE = """/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */"""

DATA_HEADER = """#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#"""

GEN_MARKER = "// Generated by tools/scripts/gluten-ut/ut_suites.py -- do not edit."

# ---------------------------------------------------------------------------
# Scala source scanning
# ---------------------------------------------------------------------------

# `class Gluten<X> extends <X> with <Trait>[ with <Trait>...] {}`, optionally
# preceded by annotations. Tolerates line breaks inside the declaration.
SHELL_RE = re.compile(
    r"(?P<anns>(?:^[ \t]*@[\w.]+(?:\([^)]*\))?[ \t]*\r?\n)*)"
    r"^[ \t]*(?:final[ \t]+)?class[ \t]+(?P<cls>\w+)\s+extends\s+(?P<base>[\w.]+)"
    r"(?P<withs>(?:\s+with\s+[\w.]+)+)\s*\{\s*\}[ \t]*$",
    re.M,
)
DECL_RE = re.compile(
    r"^[ \t]*(?:(?:abstract|final|sealed|implicit|private|protected)[ \t]+)*"
    r"(class|trait|object|case[ \t]+class|case[ \t]+object)[ \t]+(\w+)",
    re.M,
)
PACKAGE_RE = re.compile(r"^package\s+([\w.]+)\s*$", re.M)
IMPORT_RE = re.compile(r"^import\s+([\w.]+)\s*$", re.M)
STRING_RE = re.compile(r'"((?:[^"\\]|\\.)*)"')


def strip_comments(text):
    """Remove // and /* */ comments, keeping line structure (and string literals)."""
    out = []
    i, n = 0, len(text)
    while i < n:
        c = text[i]
        if c == '"':
            m = STRING_RE.match(text, i)
            if m:
                out.append(m.group(0))
                i = m.end()
                continue
            out.append(c)
            i += 1
        elif text.startswith("//", i):
            j = text.find("\n", i)
            i = n if j < 0 else j
        elif text.startswith("/*", i):
            j = text.find("*/", i)
            chunk = text[i: n if j < 0 else j + 2]
            out.append("\n" * chunk.count("\n"))
            i = n if j < 0 else j + 2
        else:
            out.append(c)
            i += 1
    return "".join(out)


def parse_string_args(args):
    """Scala argument list -> list of string values.

    Splits on top-level commas and concatenates the literals within each argument,
    so a name written across lines as `"SPARK-19471: ..." + " before using it"` stays
    one name.
    """
    values, current, depth, i, n = [], [], 0, 0, len(args)
    while i < n:
        c = args[i]
        if c == '"':
            m = STRING_RE.match(args, i)
            if not m:
                raise SystemExit("unterminated string literal in: %s" % args)
            current.append(unescape(m.group(1)))
            i = m.end()
            continue
        if c in "([{":
            depth += 1
        elif c in ")]}":
            depth -= 1
        elif c == "," and depth == 0:
            values.append("".join(current))
            current = []
        i += 1
    if current:
        values.append("".join(current))
    return values


def unescape(s):
    return (
        s.replace(r"\"", '"')
        .replace(r"\\", "\\")
        .replace(r"\n", "\n")
        .replace(r"\t", "\t")
    )


def scala_files(root):
    for dirpath, _, names in os.walk(root):
        for name in sorted(names):
            if name.endswith(".scala"):
                yield os.path.join(dirpath, name)


def scan_symbols(roots):
    """simple name -> set of fully qualified names, for every type under `roots`.

    A name declared in more than one package is kept as a set: scalac forces the
    Scala source to qualify such a reference, so `resolve` refuses to guess.
    """
    symbols = {}
    for root in roots:
        if not os.path.isdir(root):
            continue
        for path in scala_files(root):
            text = open(path, encoding="utf-8").read()
            pkg_m = PACKAGE_RE.search(text)
            if not pkg_m:
                continue
            pkg = pkg_m.group(1)
            for _, name in DECL_RE.findall(strip_comments(text)):
                symbols.setdefault(name, set()).add("%s.%s" % (pkg, name))
    return symbols


class Shell(object):
    """A generatable `class GlutenX extends X with T {}` declaration.

    `pkg` is where the generated class goes, which is usually -- but not always --
    the package of the suite it extends.
    """

    def __init__(self, pkg, cls, base_fqn, traits, anns, alt_base_pkgs=()):
        self.pkg, self.cls, self.base_fqn = pkg, cls, base_fqn
        self.traits, self.anns = traits, anns
        # Other packages the base class could have come from, when the source
        # referred to it through a wildcard import. Reported by `extract`.
        self.alt_base_pkgs = list(alt_base_pkgs)

    @property
    def base_pkg(self):
        return self.base_fqn.rsplit(".", 1)[0]


def find_shells(path, text, symbols=None):
    """Return (shells, total_decl_count) for one file.

    Trait and annotation names are fully qualified where possible: from the
    file's own imports first, then from `symbols` (types declared in gluten-ut),
    so the catalog does not depend on which package a generated class lands in.
    """
    pkg_m = PACKAGE_RE.search(text)
    if not pkg_m:
        return [], 0
    pkg = pkg_m.group(1)
    imports = {fqn.rsplit(".", 1)[-1]: fqn for fqn in IMPORT_RE.findall(text)}
    wildcards = [
        m.group(1) for m in re.finditer(r"^import\s+([\w.]+)\._\s*$", text, re.M)
    ]

    def qualify(name):
        if "." in name:
            return name
        if name in imports:
            return imports[name]
        candidates = (symbols or {}).get(name, set())
        if len(candidates) == 1:
            return next(iter(candidates))
        return name  # same-package or out of scope; leave as written

    total = len(DECL_RE.findall(strip_comments(text)))
    shells = []
    for m in SHELL_RE.finditer(text):
        cls, base = m.group("cls"), m.group("base")
        simple_base = base.rsplit(".", 1)[-1]
        if cls != "Gluten" + simple_base:
            continue  # non-conventional name: leave hand-written
        # The base class is usually in this file's package, but a handful of shells
        # import it from elsewhere. Generated code always qualifies it, so a wrong
        # guess here shows up as a compile error rather than a bad catalog entry.
        alternatives = []
        if "." in base:
            base_fqn = base
        elif base in imports:
            base_fqn = imports[base]
        else:
            base_fqn = "%s.%s" % (pkg, base)
            alternatives = [w for w in wildcards if w != pkg]
        traits = [qualify(t) for t in re.findall(r"with\s+([\w.]+)", m.group("withs"))]
        anns = [qualify(a) for a in re.findall(r"@([\w.]+)", m.group("anns") or "")]
        shells.append(Shell(pkg, cls, base_fqn, traits, anns, alternatives))
    return shells, total


# ---------------------------------------------------------------------------
# Catalog (suites.txt)
# ---------------------------------------------------------------------------
# One line per generated suite:
#     <vanilla suite FQN> | <trait FQN>[,...] [| ann=<FQN>[,...]] [| pkg=<package>]
# The generated class is <vanilla package>.Gluten<vanilla simple name> unless `pkg=`
# says otherwise.


def catalog_line(shell):
    line = "%s | %s" % (shell.base_fqn, ",".join(shell.traits))
    if shell.anns:
        line += " | ann=%s" % ",".join(shell.anns)
    if shell.pkg != shell.base_pkg:
        line += " | pkg=%s" % shell.pkg
    return line


def parse_catalog(path):
    entries = []
    for lineno, raw in enumerate(open(path, encoding="utf-8"), 1):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        parts = [p.strip() for p in line.split("|")]
        if len(parts) < 2:
            raise SystemExit("%s:%d: expected '<suite> | <traits>': %s" % (path, lineno, line))
        base_fqn, traits = parts[0], [t for t in parts[1].split(",") if t]
        options = {}
        for extra in parts[2:]:
            if "=" not in extra:
                raise SystemExit("%s:%d: expected 'key=value', got '%s'" % (path, lineno, extra))
            key, value = extra.split("=", 1)
            options[key.strip()] = value.strip()
        unknown = set(options) - {"ann", "pkg"}
        if unknown:
            raise SystemExit("%s:%d: unknown option(s) %s" % (path, lineno, sorted(unknown)))
        base_pkg, simple = base_fqn.rsplit(".", 1)
        anns = [a for a in options.get("ann", "").split(",") if a]
        entries.append(
            Shell(options.get("pkg", base_pkg), "Gluten" + simple, base_fqn, traits, anns)
        )
    return entries


def render_shell(shell):
    body = [LICENSE, "", GEN_MARKER, "package %s" % shell.pkg, ""]
    for ann in shell.anns:
        body.append("@%s" % ann)
    body.append(
        "class %s extends %s with %s {}"
        % (shell.cls, shell.base_fqn, " with ".join(shell.traits))
    )
    return "\n".join(body) + "\n"


# ---------------------------------------------------------------------------
# Backend settings (settings-<backend>.txt)
# ---------------------------------------------------------------------------
# One directive per line. `#` at the start of a line is a comment; reasons for an
# exclusion are kept as comments directly above it, as they are in the Scala today.
#
#     enable          <suite FQN>
#     disable         <suite FQN> -- <reason>
#     exclude         <suite FQN>#<test name>
#     excludePrefix   <suite FQN>#<test name prefix>
#     include         <suite FQN>#<test name>
#     includePrefix   <suite FQN>#<test name prefix>
#     excludeGluten   <suite FQN>#<test name>        ("Gluten - " prefixed test)
#     includeGluten   <suite FQN>#<test name>
#     excludeGlutenPrefix <suite FQN>#<test name prefix>
#     includeAllGluten    <suite FQN>

DSL_TO_DIRECTIVE = {
    "exclude": "exclude",
    "excludeCH": "exclude",
    "excludeByPrefix": "excludePrefix",
    "include": "include",
    "includeCH": "include",
    "includeByPrefix": "includePrefix",
    "excludeGlutenTest": "excludeGluten",
    "includeGlutenTest": "includeGluten",
    "excludeGlutenTestsByPrefix": "excludeGlutenPrefix",
    "includeGlutenTestsByPrefix": "includeGlutenPrefix",
    "excludeAllGlutenTests": "excludeAllGluten",
    "includeAllGlutenTests": "includeAllGluten",
}
SUITE_ONLY_DIRECTIVES = {"enable", "excludeAllGluten", "includeAllGluten"}

STMT_START_RE = re.compile(r"^\s*(enableSuite|disableSuite|\.[a-zA-Z])")
ENABLE_RE = re.compile(r"^enableSuite(?:\[(?P<tag>[\w.]+)\]|\((?P<str>.*?)\))")
DISABLE_RE = re.compile(r"^disableSuite(?:\[(?P<tag>[\w.]+)\]|\((?P<str>[^,]*?),)")
CALL_RE = re.compile(r"\.(?P<name>[a-zA-Z]+)\((?P<args>.*?)\)\s*$", re.S)

IGNORABLE_RE = re.compile(
    r"^\s*(package\s|import\s|//|/\*|\*|class\s+\w+TestSettings|"
    r"override\s+def\s+getSQLQueryTestSettings|\}|\)|$)"
)


def logical_statements(lines):
    """Group physical lines into DSL statements, yielding (start_line, text)."""
    i, n = 0, len(lines)
    while i < n:
        if STMT_START_RE.match(lines[i]):
            start, buf, depth = i, [], 0
            while i < n:
                buf.append(lines[i])
                depth += lines[i].count("(") - lines[i].count(")")
                i += 1
                if depth <= 0:
                    break
            yield start, "\n".join(buf)
        else:
            yield i, None
            i += 1


def parse_settings(path, symbols):
    """Parse a *TestSettings.scala into ordered (directive, suite, arg, comments)."""
    text = open(path, encoding="utf-8").read()
    lines = text.split("\n")
    entries, pending, unconsumed = [], [], []
    calls_consumed = [0]
    current = None

    def resolve(name):
        if "." in name:
            return name
        candidates = symbols.get(name, set())
        if not candidates:
            raise SystemExit("%s: cannot resolve suite class '%s'" % (path, name))
        if len(candidates) > 1:
            raise SystemExit(
                "%s: '%s' is declared in %s -- qualify it in the Scala source"
                % (path, name, sorted(candidates))
            )
        return next(iter(candidates))

    for start, stmt in logical_statements(lines):
        if stmt is None:
            line = lines[start]
            stripped = line.strip()
            if stripped.startswith("//"):
                comment = stripped[2:].strip()
                if comment and not comment.startswith("scalastyle:"):
                    pending.append(comment)
            elif re.match(r"\s*class\s+\w+TestSettings", line):
                pending = []  # file-level notes, not a reason for a directive
            elif not IGNORABLE_RE.match(line):
                unconsumed.append((start + 1, line))
            continue

        body = strip_comments(stmt).strip()
        m = ENABLE_RE.match(body)
        if m:
            name = m.group("tag") or unescape(STRING_RE.search(m.group("str")).group(1))
            current = resolve(name)
            entries.append(("enable", current, None, pending))
            pending = []
            body = body[m.end():].strip()
        else:
            m = DISABLE_RE.match(body)
            if m:
                name = m.group("tag") or unescape(STRING_RE.search(m.group("str")).group(1))
                suite = resolve(name)
                reason = " ".join(
                    unescape(s) for s in STRING_RE.findall(body[m.end():])
                ).strip()
                entries.append(("disable", suite, reason, pending))
                pending, current = [], None
                continue

        # Chained .exclude(...) / .include(...) calls on the current suite.
        while body:
            call = CALL_RE.search(body)
            if not call:
                if body.strip():
                    unconsumed.append((start + 1, body))
                break
            name, args = call.group("name"), call.group("args")
            if name not in DSL_TO_DIRECTIVE:
                unconsumed.append((start + 1, ".%s(...)" % name))
                break
            if current is None:
                raise SystemExit("%s:%d: .%s() without an enabled suite" % (path, start + 1, name))
            directive = DSL_TO_DIRECTIVE[name]
            calls_consumed[0] += 1
            values = [v for v in parse_string_args(args) if v]
            if not values:
                entries.append((directive, current, None, pending))
            else:
                for idx, value in enumerate(values):
                    entries.append((directive, current, value, pending if idx == 0 else []))
            pending = []
            body = body[: call.start()].strip()

    return entries, unconsumed, calls_consumed[0]


def render_settings(entries, backend, spark):
    out = [
        DATA_HEADER,
        "# Gluten unit test settings for the %s backend, Spark %s." % (backend, spark),
        "#",
        "# Read at run time by org.apache.gluten.utils.DataFileBackendTestSettings.",
        "# One directive per line; see tools/scripts/gluten-ut/ut_suites.py for the format.",
        "#",
        "#   enable <suite>                     run this suite",
        "#   disable <suite> -- <reason>        never run it",
        "#   exclude <suite>#<test>             run the suite except this test",
        "#   excludePrefix <suite>#<prefix>     ...except tests starting with <prefix>",
        "#   include <suite>#<test>             run only this test (mutually exclusive",
        "#                                      with exclude, per suite)",
        "#",
        "# A test name is everything after the first '#'. Comment lines directly above a",
        "# directive are its reason, and are preserved by the extractor.",
        "",
    ]
    width = max(
        [len(d) for d, _, _, _ in entries] + [len("excludeGlutenPrefix")]
    )
    for directive, suite, arg, comments in entries:
        if directive == "enable":
            out.append("")
        for comment in comments:
            out.append("# %s" % comment)
        pad = directive.ljust(width)
        if directive == "disable":
            out.append("%s %s -- %s" % (pad, suite, arg))
        elif arg is None:
            out.append("%s %s" % (pad, suite))
        else:
            out.append("%s %s#%s" % (pad, suite, arg))
    return "\n".join(out).strip() + "\n"


# ---------------------------------------------------------------------------
# Subcommands
# ---------------------------------------------------------------------------


def cmd_extract(args):
    module = args.module.rstrip("/")
    scala_root = os.path.join(module, "src/test/scala")
    out_dir = os.path.join(module, "src/test/resources/gluten-ut")
    os.makedirs(out_dir, exist_ok=True)
    symbols = scan_symbols([scala_root, os.path.join(module, "../common/src/test/scala")])

    # 1. Catalog: every conventional shell in a file that contains nothing else.
    shells, mixed, skipped_files = [], [], []
    for path in scala_files(scala_root):
        text = open(path, encoding="utf-8").read()
        found, total = find_shells(path, text, symbols)
        if not found:
            continue
        if len(found) == total:
            shells.extend(found)
            skipped_files.append(path)
        else:
            mixed.extend(found)

    shells.sort(key=lambda s: s.base_fqn)
    catalog_path = os.path.join(out_dir, "suites.txt")

    # Re-running extract must not undo a correction made to the catalog by hand
    # (the base package of a suite reached through a wildcard import cannot always
    # be inferred), and must not lose entries whose sources have already been
    # pruned. Both are covered by carrying the existing catalog forward.
    if os.path.exists(catalog_path):
        previous = parse_catalog(catalog_path)
        by_gen = {"%s.%s" % (s.pkg, s.cls): s for s in shells}
        for old in previous:
            gen_fqn = "%s.%s" % (old.pkg, old.cls)
            found = by_gen.get(gen_fqn)
            if found is None:
                shells.append(old)  # source already pruned
            elif found.base_fqn != old.base_fqn and found.alt_base_pkgs:
                found.base_fqn = old.base_fqn  # keep the reviewed package
        shells.sort(key=lambda s: s.base_fqn)

    # Everything is parsed before anything is written, so a failure below cannot
    # leave a half-migrated data file behind.
    settings_files = []
    for backend in args.backends:
        cls = {"velox": "Velox", "clickhouse": "ClickHouse", "bolt": "Bolt"}[backend]
        if args.settings_scala:
            if len(args.backends) != 1:
                raise SystemExit("--settings-scala needs exactly one --backends value")
            settings_scala = args.settings_scala
        else:
            settings_scala = os.path.join(
                scala_root, "org/apache/gluten/utils", backend, "%sTestSettings.scala" % cls
            )
        if not os.path.exists(settings_scala):
            print("  skip %s: %s not found" % (backend, settings_scala))
            continue
        catalog_symbols = dict(symbols)
        for shell in shells:
            catalog_symbols.setdefault(shell.cls, set()).add("%s.%s" % (shell.pkg, shell.cls))
        entries, unconsumed, calls_consumed = parse_settings(settings_scala, catalog_symbols)
        if unconsumed:
            print("  ERROR: %d unparsed line(s) in %s:" % (len(unconsumed), settings_scala))
            for lineno, line in unconsumed[:20]:
                print("    %d: %s" % (lineno, line.strip()))
            return 1
        settings_files.append((backend, settings_scala, entries, calls_consumed))

    with open(catalog_path, "w", encoding="utf-8") as fh:
        fh.write(DATA_HEADER + "\n")
        fh.write("# Vanilla Spark suites that Gluten runs through a generated subclass:\n")
        fh.write("#\n")
        fh.write("#   <vanilla suite> | <trait>[,<trait>...] [| <annotation>,...]\n")
        fh.write("#\n")
        fh.write("# generates, at build time (see tools/scripts/gluten-ut/ut_suites.py):\n")
        fh.write("#\n")
        fh.write("#   class Gluten<Suite> extends <Suite> with <trait> {}\n")
        fh.write("#\n")
        fh.write("# Whether a generated suite actually runs is decided per backend, in\n")
        fh.write("# settings-<backend>.txt.\n\n")
        for shell in shells:
            fh.write(catalog_line(shell) + "\n")
    print("catalog: %s (%d suites, from %d files)" % (catalog_path, len(shells), len(skipped_files)))
    ambiguous = [s for s in shells if s.alt_base_pkgs]
    if ambiguous:
        print(
            "  %d suite(s) reached their base class through a wildcard import; the catalog\n"
            "  assumed the same package. A wrong guess is a compile error, not a silent\n"
            "  mistake -- check these, and correct the line if the build complains:"
            % len(ambiguous)
        )
        for shell in ambiguous:
            print(
                "    %s  (or: %s)"
                % (shell.base_fqn, ", ".join("%s.%s" % (p, shell.base_fqn.rsplit(".", 1)[-1])
                                             for p in shell.alt_base_pkgs))
            )
    if mixed:
        print(
            "  %d shell(s) left hand-written: declared in a file that holds other code too"
            % len(mixed)
        )

    # 2. Per-backend settings.
    for backend, settings_scala, entries, calls_consumed in settings_files:
        spark = re.search(r"spark(\d)(\d)", module)
        spark = "%s.%s" % spark.groups() if spark else "?"
        path = os.path.join(out_dir, "settings-%s.txt" % backend)
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(render_settings(entries, backend, spark))
        counts = {}
        for directive, _, _, _ in entries:
            counts[directive] = counts.get(directive, 0) + 1
        print("settings: %s (%s)" % (path, ", ".join(
            "%d %s" % (n, d) for d, n in sorted(counts.items(), key=lambda kv: -kv[1]))))

        # Independent cross-check: count the DSL call sites with a plain regex and
        # confirm the parser consumed every one of them. Test names themselves are
        # checked by VeloxSettingsMigrationSuite, which compares the run/skip
        # decision of the old and new settings for every name they mention.
        raw = strip_comments(open(settings_scala, encoding="utf-8").read())
        call_sites = len(re.findall(r"\.(%s)\(" % "|".join(DSL_TO_DIRECTIVE), raw))
        status = "OK" if call_sites == calls_consumed else "MISMATCH"
        print(
            "  cross-check: %d DSL call site(s) in Scala, %d consumed -- %s"
            % (call_sites, calls_consumed, status)
        )
        if status == "MISMATCH":
            return 1
    return 0


def cmd_generate(args):
    catalog = parse_catalog(args.catalog)
    written = 0
    for shell in catalog:
        target_dir = os.path.join(args.out, *shell.pkg.split("."))
        os.makedirs(target_dir, exist_ok=True)
        path = os.path.join(target_dir, "%s.scala" % shell.cls)
        content = render_shell(shell)
        if os.path.exists(path) and open(path, encoding="utf-8").read() == content:
            continue
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(content)
        written += 1
    print(
        "gluten-ut: %d suites in catalog, %d source file(s) written to %s"
        % (len(catalog), written, args.out)
    )
    return 0


def cmd_verify(args):
    """Prove the catalog reproduces the hand-written shells exactly."""
    module = args.module.rstrip("/")
    scala_root = os.path.join(module, "src/test/scala")
    symbols = scan_symbols([scala_root, os.path.join(module, "../common/src/test/scala")])
    # Keyed by the generated suite's own name: that is what the settings file and
    # the CI reports refer to. The base class is compared by simple name, because
    # a wildcard import in the source can leave its package ambiguous (see the
    # warning `extract` prints); a wrong package is caught by the compiler.
    def key(shell):
        return "%s.%s" % (shell.pkg, shell.cls)

    catalog = {key(s): s for s in parse_catalog(args.catalog)}
    existing = {}
    for path in scala_files(scala_root):
        text = open(path, encoding="utf-8").read()
        found, total = find_shells(path, text, symbols)
        for shell in found:
            if len(found) == total:
                existing[key(shell)] = shell

    missing = sorted(set(existing) - set(catalog))
    extra = sorted(set(catalog) - set(existing))
    differing = []
    for fqn, shell in sorted(existing.items()):
        gen = catalog.get(fqn)
        if gen is None:
            continue
        simple = lambda s: s.base_fqn.rsplit(".", 1)[-1]
        if (simple(gen), gen.traits, gen.anns) != (simple(shell), shell.traits, shell.anns):
            differing.append(fqn)

    print("verify: %d hand-written shells, %d in catalog" % (len(existing), len(catalog)))
    for label, items in (("missing from catalog", missing), ("not in sources", extra),
                         ("declaration differs", differing)):
        if items:
            print("  %s (%d):" % (label, len(items)))
            for item in items[:20]:
                print("    %s" % item)
    ok = not (missing or extra or differing)
    print("verify: %s" % ("OK -- catalog reproduces every shell" if ok else "FAILED"))
    return 0 if ok else 1


def cmd_prune(args):
    """Delete the hand-written sources the catalog now generates."""
    module = args.module.rstrip("/")
    scala_root = os.path.join(module, "src/test/scala")
    symbols = scan_symbols([scala_root, os.path.join(module, "../common/src/test/scala")])
    catalog = {"%s.%s" % (s.pkg, s.cls) for s in parse_catalog(args.catalog)}
    removable, kept = [], []
    for path in scala_files(scala_root):
        text = open(path, encoding="utf-8").read()
        found, total = find_shells(path, text, symbols)
        if not found:
            continue
        if len(found) == total and all(
            "%s.%s" % (s.pkg, s.cls) in catalog for s in found
        ):
            removable.append(path)
        else:
            kept.append(path)
    for path in removable:
        if args.apply:
            os.remove(path)
        print("%s %s" % ("removed" if args.apply else "would remove", path))
    print(
        "prune: %d file(s) %s, %d file(s) kept (shells mixed with other code)"
        % (len(removable), "removed" if args.apply else "to remove", len(kept))
    )
    if not args.apply:
        print("prune: re-run with --apply to delete them")
    return 0


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest="cmd")

    p = sub.add_parser("extract", help="Scala sources -> data files")
    p.add_argument("--module", required=True, help="e.g. gluten-ut/spark35")
    p.add_argument("--backends", nargs="+", default=["velox", "clickhouse", "bolt"])
    p.add_argument(
        "--settings-scala",
        help="read the settings from this file instead of the conventional path "
        "(useful once the original has been renamed, e.g. *TestSettingsLegacy.scala)",
    )
    p.set_defaults(func=cmd_extract)

    p = sub.add_parser("generate", help="catalog -> Scala sources")
    p.add_argument("--catalog", required=True)
    p.add_argument("--out", required=True)
    p.set_defaults(func=cmd_generate)

    p = sub.add_parser("verify", help="diff catalog against hand-written sources")
    p.add_argument("--module", required=True)
    p.add_argument("--catalog", required=True)
    p.set_defaults(func=cmd_verify)

    p = sub.add_parser("prune", help="delete hand-written sources the catalog now generates")
    p.add_argument("--module", required=True)
    p.add_argument("--catalog", required=True)
    p.add_argument("--apply", action="store_true", help="actually delete (default: dry run)")
    p.set_defaults(func=cmd_prune)

    args = parser.parse_args()
    if not args.cmd:
        parser.print_help()
        return 2
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
